In [1]:
import pandas as pd

In [2]:
scores = pd.Series([85, 90, 78, 92])
print(scores)

0    85
1    90
2    78
3    92
dtype: int64

In [3]:
print(type(scores))
print(scores.index)
print(scores.values)

<class 'pandas.Series'>
RangeIndex(start=0, stop=4, step=1)
[85 90 78 92]

In [5]:
scores = pd.Series(
    [85, 90, 78],
    index= ["student_a", "student_b", "student_c"]
)
print(scores)

student_a    85
student_b    90
student_c    78
dtype: int64

In [6]:
print(scores["student_b"])

90

In [7]:
student = {
    "name": "Daniel",
    "age": 24,
    "course": "Data Engineering"
}
print(student["name"])

Daniel

In [23]:
data = {
    "Name": ["Daniel", "Sara", "David"],
    "Age": [24, 27, 22],
    "Score": [85, 91, 78]
}

df = pd.DataFrame(data)
df

     Name  Age  Score
0  Daniel   24     85
1    Sara   27     91
2   David   22     78

In [13]:
print(type(df))
print(df.columns)
print(df.index)
print(df.shape)

<class 'pandas.DataFrame'>
Index(['Name', 'Age', 'Score'], dtype='str')
RangeIndex(start=0, stop=3, step=1)
(3, 3)

In [14]:
data = [
    {"Name": "Daniel", "Age": 24, "Score": 85},
    {"Name": "Sara", "Age": 27, "Score": 91},
    {"Name": "David", "Age": 22, "Score": 78}
]

df2 = pd.DataFrame(data)
df2

     Name  Age  Score
0  Daniel   24     85
1    Sara   27     91
2   David   22     78

In [16]:
df.equals(df2)
print(type(df2))
print(df2.columns)
print(df2.index)
print(df2.shape)

<class 'pandas.DataFrame'>
Index(['Name', 'Age', 'Score'], dtype='str')
RangeIndex(start=0, stop=3, step=1)
(3, 3)

In [25]:
print(df["Name"])
print(type(df["Name"]))

0    Daniel
1      Sara
2     David
Name: Name, dtype: str
<class 'pandas.Series'>

In [28]:
print(df[["Name", "Score"]])
print(type(df[["Name"]]))

     Name  Score
0  Daniel     85
1    Sara     91
2   David     78
<class 'pandas.DataFrame'>

In [30]:
print(df.index)
df.index = ["student_1", "student_2", "student_3"]
df

RangeIndex(start=0, stop=3, step=1)

             Name  Age  Score
student_1  Daniel   24     85
student_2    Sara   27     91
student_3   David   22     78

In [44]:
df.loc["student_1"]

Name      Daniel
Age           24
Score         90
Passed      True
Name: student_1, dtype: object

In [33]:
df.iloc[0]

Name     Daniel
Age          24
Score        85
Name: student_1, dtype: object

In [34]:
df["Passed"] = [True, True, False]
df

             Name  Age  Score  Passed
student_1  Daniel   24     85    True
student_2    Sara   27     91    True
student_3   David   22     78   False

In [35]:
df["Score"] = df["Score"] + 5
df

             Name  Age  Score  Passed
student_1  Daniel   24     90    True
student_2    Sara   27     96    True
student_3   David   22     83   False

In [36]:
df["Score"] > 90

student_1    False
student_2     True
student_3    False
Name: Score, dtype: bool

In [37]:
df[df["Score"] > 90]

           Name  Age  Score  Passed
student_2  Sara   27     96    True

In [38]:
csv_text = """Name,Age,City
Daniel,24,Haifa
Sara,27,Jerusalem
David,22,Tel Aviv
"""

with open("students.csv", "w") as f:
    f.write(csv_text)

In [40]:
csv_df = pd.read_csv("students.csv")
csv_df

     Name  Age       City
0  Daniel   24      Haifa
1    Sara   27  Jerusalem
2   David   22   Tel Aviv

In [41]:
print(type(csv_df))
print(csv_df.columns)
print(csv_df.index)
print(csv_df.shape)

<class 'pandas.DataFrame'>
Index(['Name', 'Age', 'City'], dtype='str')
RangeIndex(start=0, stop=3, step=1)
(3, 3)

In [42]:
json_text = """[
    {"Name": "Daniel", "Age": 24, "City": "Haifa"},
    {"Name": "Sara", "Age": 27, "City": "Jerusalem"},
    {"Name": "David", "Age": 22, "City": "Tel Aviv"}
]
"""

with open("students.json", "w") as f:
    f.write(json_text)

In [43]:
json_df = pd.read_json("students.json")
json_df

     Name  Age       City
0  Daniel   24      Haifa
1    Sara   27  Jerusalem
2   David   22   Tel Aviv

In [47]:
import requests

response = requests.get("https://jsonplaceholder.typicode.com/todos?_limit=5")
data = response.json()

api_df = pd.DataFrame(data)
api_df

   userId  id                                              title  completed
0       1   1                                 delectus aut autem      False
1       1   2                 quis ut nam facilis et officia qui      False
2       1   3                                fugiat veniam minus      False
3       1   4                                   et porro tempora       True
4       1   5  laboriosam mollitia et enim quasi adipisci qui...      False

In [51]:
api_df.head()
print(api_df.columns)
api_df.shape

Index(['userId', 'id', 'title', 'completed'], dtype='str')

(5, 4)